/* prettier-ignore-start */

/* eslint-disable */
/**
 * Generated `dataModel` utility.
 *
 * THIS CODE IS AUTOGENERATED, DO NOT EDIT.
 *
 * To update this file, run `npx convex dev`.
 *
 * @module
 */

import type { GenericDataModel } from "convex/server";

/**
 * The data model is empty for now.
 * Schema will be defined in Milestone 6.
 */
export type DataModel = GenericDataModel<DocumentTypes, "id">;

/* prettier-ignore-end */
